commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("listing", include("listing.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/listing/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "listing"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:listing_id>", views.list, name="listing"),



]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models






class User(AbstractUser):
    pass

commerce/listing/models.py
from django.db import models


# Create your models here.

class Listing(models.Model):
    title = models.CharField(max_length=64, )
    description = models.CharField(max_length=64)
    starting = models.IntegerField()
    imagen = models.ImageField(null=True, blank=True)
    comentarios = models.CharField(max_length=300, null=True)

    def __str__(self):
        return f"{self.id}: {self.title} starting in {self.starting}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User


def index(request):
    return render(request, "auctions/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

commerce/listing/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import Listing
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='login')
def index(request):
    return render(request, "listing/index.html", {
        "listing": Listing.objects.all()
    })


@login_required(login_url='login')
def listing(request, listing_id):
    list = Listing.objects.get(id=listing_id)
    return render(request, "listing/list.html", {
        "flight": list,

    })
@login_required(login_url='login')
def list(request, listing_id):
    return render(request, "listing/list.html", {
        "listing": Listing.objects.get(id=listing_id),

    })

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

    <a href={%  url 'listing:index' %}> Active Listings</a>


{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="static/listing/styles.css" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

commerce/listing/templates/listing/index.html
{% extends "listing/layout.html" %}


{% block body %}

<div style="float: left">



    <h1> Auction Listings:   <a style="color: lightyellow" href='http://127.0.0.1:8000/' >Perfil</a>              </h1>

        {% for listing in listing %}

    <a href="{% url 'listing:listing' listing.id %}">
        <h2>{{ listing.title }}, puja minima {{ listing.starting }} dolares </h2>


            <img src="images/{{ listing.imagen }}", width="400"
                 height="341"> </a>

        {% endfor %}
</div>



<div style="float: right" >
    <button > Crear subasta</button>
</div>




{% endblock %}

commerce/listing/templates/listing/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../../../static/listing/styles.css">

    <title>Title</title>
</head>
<body>


{% block body %}
{% endblock %}
</body>
</html>

commerce/listing/templates/listing/list.html
{% extends "listing/layout.html" %}

{% block body %}

<h1>{{ listing.title }}</h1>
<ul>

    <li>title: {{ listing.title }} </li>
    <li>description: {{ listing.description }}</li>
    <li>starting: {{ listing.starting }} $</li>

</ul>

    <hr>

<img src="images/{{ listing.imagen }}", width="400"
     height="341">

<hr>

<p>  {{ listing.comentarios }} </p>

 <a href={%  url 'listing:index' %}> ver listas   </a>

{% endblock %}